name: Cypress Multi Browser Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  cypress-run:
    name: Cypress (${{ matrix.browser }} - Shard ${{ matrix.shardIndex }}/${{ matrix.shardTotal }})
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        browser: [chrome, firefox, edge]
        shardIndex: [1, 2]
        shardTotal: [2]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: |
          mkdir -p allure-results
          npm install

      - name: Run Cypress Tests
        run: |
          npx cypress run \
            --browser ${{ matrix.browser }} \
            --env allure=true

      - name: Upload Allure Results Artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results-${{ matrix.browser }}-shard${{ matrix.shardIndex }}
          path: allure-results
          if-no-files-found: ignore
          retention-days: 7
